import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Login from '../components/Login'


export default function Home({session}) {
  if (!session) return <Login />
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const session = await getSession(contact);
  
  return {
    props: {
      session
    }
  }
}
